---
- name: Retrieve and Configure kubeconfig
  hosts: masters
  become: yes
  tasks:
    - name: "Change /etc/kubernetes directory ownership"
      file:
        path: "/etc/kubernetes"
        state: directory
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        recurse: yes

    - name: Fetch kubeconfig file from master node
      fetch:
        src: "/etc/kubernetes/admin.conf"
        dest: "/tmp/cluster-homelab.conf"
        flat: yes

- hosts: local
  tasks:
    - name: Create kubernetes folder
      file:
        path: "/etc/kubernetes" 
        state: directory

    - name: Ensure .kube directory exists in user's home
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'

    - name: Move kubeconfig to local .kube directory
      copy:
        src: "/tmp/cluster-homelab.conf"
        dest: "{{ ansible_env.HOME }}/.kube/config"
        mode: '0644'

    - name: Set KUBECONFIG environment variable in the user's shell profile
      lineinfile:
        path: "{{ ansible_env.HOME }}/{{ ansible_env.SHELL | regex_replace('.*/', '.') }}rc"
        line: "export KUBECONFIG=$HOME/.kube/config"
        create: yes
