---
- name: Retrieve and Configure kubeconfig
  hosts: masters
  tasks:
    - name: Fetch kubeconfig file from master node
      fetch:
        src: "/etc/kubernetes/admin.conf"
        dest: "/home/{{ ansible_user }}/kubeconfig/admin.conf"
        flat: yes

- hosts: local
  become: yes
  tasks:
    - name: Ensure .kube directory exists in user's home
      file:
        path: "{{ ansible_env.HOME }}/.kube"
        state: directory
        mode: '0755'

    - name: Move kubeconfig to local .kube directory
      copy:
        src: "{{ playbook_dir }}/kubeconfig/admin.conf"
        dest: "{{ ansible_env.HOME }}/.kube/config"
        mode: '0644'

    - name: Set KUBECONFIG environment variable in the user's shell profile
      lineinfile:
        path: "{{ ansible_env.HOME }}/{{ ansible_env.SHELL | regex_replace('.*/', '.') }}rc"
        line: "export KUBECONFIG=$HOME/.kube/config"
        create: yes

