---

- hosts: proxmox
  become: true
  remote_user: "{{ new_admin_user }}"
  roles:
    - proxmox

- hosts:
    - masters
    - workers
  become: true
  roles:
    - common
    - docker
    - kubernetes

- hosts: masters
  become: true
  roles:
    - master
    - helm

- hosts: workers
  become: true
  roles:
    - worker
