---
- hosts:
    - masters
    - workers
  become: true
  roles:
    - common
    - docker

- hosts: masters
  become: true
  roles:
    - master

- hosts: workers
  become: true
  roles:
    - worker
