---
- hosts: all
  become: yes
  remote_user: "{{ new_admin_user }}"
  roles:
    - common
    - docker
    - kubernetes

- hosts: masters
  become: yes
  remote_user: "{{ new_admin_user }}"
  roles:
    - master
