hostname: ${hostname}
fqdn: ${hostname}.${domain}
manage_etc_hosts: true
users:
  - name: ubuntu
    sudo: ALL=(ALL) NOPASSWD:ALL
    groups: sudo
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCmUr9EjfAU+uF1Z/fEge91JDW/a3GK2XQBfhKjCpJMDBtnoLQcWWRSROT0nXJ7sh6IM7K9/wjBgzDmBOY2BxBSbjYzdniTMub/r+e41Us82JbLt9fpo1OAH0q44EqzmuBz0VC0H+pIc1m7PqylS7rq3wgeNFWR5Qg8RHx7aUaSdeJLtyuwJzKHE+QGmbeogL0jeQ5nlYGEoMW9cNotifOG9DHmR4d7FjjqbyPHjsGZ4xVv1eCMOW/dIMOBJD+9KPHSSGaVImCLs2BVmAu5EHe0lKs0hRtqc2mbX4HtzRs/grrY2IVjTScFkDy7vMzRVBh6EpahkLORHtHRWwcRfC2J+aUSjyKQVjopzyoYpYiLR2C3pUhVss8rfL/3WJjGgQ+B6LHVcmrGCOlrd2pky2y5EfDfFluQlt1/SXl8PMAjEh0z21tmMjum4R8pR/KrNbKSV9XDtK6KSh9V9y2hnubV+WXp5VnobTOPWVQGND2gYFXOtnKZn00xeC1EuWsmD1FdoH36JLKZpLFL5Pzr6IWGn7AoOxjHrzJ5so+zJmthD/WUXnIA0MPYfuo2s7dihTcrHMutGrGZ1mO28pzp9pYG8OLI9meISXzq6xuZS+QenHgzQzSpmUZm2jLOIFDCCvtQ5t50oqLmpdR4jApx4L6rxNx33liQpwx0qGd86PY9Dw==
package_upgrade: true
write_files:
  - path: /etc/motd
    content: |
      Welcome to your Kubernetes node provisioned by Terraform
runcmd:
  - [ sh, -c, "echo Hello, Terraform provisioned Kubernetes Node!" ]
