---

proxmox_hostname: "homelab"
proxmox_ipv4: "192.168.1.100"
proxmox_ipv4_with_cidr: "{{ proxmox_ipv4 }}/24"
proxmox_gateway: "192.168.1.1"
proxmox_bridge_interface: "enp42s0"

motd_repo_url: "https://github.com/0xBingo/motd"
motd_clone_path: "/srv/motd"
motd_branch : "master"

motd_scripts_path: "/etc/update-motd.d"

