---

- name: Deploy template.sh
  template:
    src: "template.sh.j2"
    dest: "/home/{{ new_admin_user }}/template.sh"
    owner: "{{ new_admin_user }}"
    group: "{{ new_admin_user }}"
    mode: "0644"

- name: Execute template.sh
  shell: "bash /home/{{ new_admin_user }}/template.sh"
