---

- name: Update apt package index
  apt:
    update_cache: yes

- name: Install OpenSSH Server (if not installed)
  apt:
    name: 
      - openssh-server
    state: present

- name: Ensure sudo package exists
  apt:
    name: sudo
    state: present

- name: Add the Ansible user to the sudoers file
  lineinfile:
    dest: /etc/sudoers
    line: "{{ new_admin_user }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'

- name: Add admin user to sudoers
  copy:
    content: "{{ new_admin_user }} ALL=(ALL) NOPASSWD: ALL"
    dest: /etc/sudoers.d/{{ new_admin_user }}_sudoers
    mode: '0440'

- name: Create new admin user without password
  user:
    name: "{{ new_admin_user }}"
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_type: rsa
    groups: sudo
    append: true
    state: present
    shell: /bin/bash

- name: Add admin SSH public keys
  authorized_key:
    user: "{{ new_admin_user }}"
    key: "{{ item }}"
  loop: "{{ admin_ssh_pub_keys }}"

- name: Ensure SSH service is running and enabled
  service:
    name: sshd
    state: restarted
    enabled: yes
