---
- name: Create Terraform role for Proxmox provisioning
  shell: >
    pveum role add TerraformProv -privs "Datastore.Allocate Datastore.AllocateSpace Datastore.Audit Pool.Allocate Sys.Audit Sys.Console Sys.Modify VM.Allocate VM.Audit VM.Clone VM.Config.CDROM VM.Config.Cloudinit VM.Config.CPU VM.Config.Disk VM.Config.HWType VM.Config.Memory VM.Config.Network VM.Config.Options VM.Console VM.Migrate VM.Monitor VM.PowerMgmt SDN.Use"
  register: result_role
  failed_when: "'already exists' not in result_role.stderr and result_role.rc != 0"

- name: Create Proxmox user for Terraform
  shell: "pveum user add terraform@pve --password {{ terraform_user_password }}"
  register: result_user
  failed_when: "'already exists' not in result_user.stderr and result_user.rc != 0"

- name: Assign Terraform role to Proxmox user
  shell: "pveum aclmod / -user terraform@pve -role TerraformProv"
  register: result_acl
  failed_when: "'already exists' not in result_acl.stderr and result_acl.rc != 0"

- name: Create Terraform API Token for Proxmox
  shell: pveum user token add terraform@pve terraform -expire 0 -privsep 0 -comment "Terraform token"
  register: token_creation_result
  failed_when: "'already exists' not in result_acl.stderr and result_acl.rc != 0"

- name: Output the result of Terraform API token creation
  debug:
    msg: "{{ token_creation_result }}"
