---

# Kube configuration

- name: "Create .kube directory"
  file:
    path: "{{ item }}/.kube"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - "/home/{{ ansible_user }}"
    - "/root"

- name: "Copy admin configuration to home kube directory"
  copy:
    src: "/etc/kubernetes/admin.conf"
    dest: "{{ item }}/.kube/config"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    remote_src: true
    force: yes
    mode: '0600'
  loop:
    - "/home/{{ ansible_user }}"
    - "/root"

- name: "Add permissions path for {{ ansible_user }}"
  command: "chown {{ ansible_user }}:{{ ansible_user }} /home/{{ ansible_user }}/.kube/config"

- name: Set KUBECONFIG environment variable in the user's shell profile
  lineinfile:
    path: "{{ item }}/.bashrc"
    line: "export KUBECONFIG=/home/{{ ansible_user }}/.kube/config"
    create: yes
  loop:
    - "/home/{{ ansible_user }}"
    - "/root"

# Aliases configuration

- name: Deploy aliases
  template:
    src: "aliases.j2"
    dest: "/home/{{ ansible_user }}/.bash_aliases"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

#- name: Ensure .bashrc sources .bash_aliases
#  lineinfile:
#    path: "/home/{{ ansible_user }}/.bashrc"
#    owner: "{{ ansible_user }}"
#    group: "{{ ansible_user }}"
#    mode: "0644"
#    line: "source /home/{{ ansible_user }}/.bash_aliases"
#    insertafter: "EOF"
#    state: present

# Install calico

- name: Install calico pod network
  become: false
  command: kubectl apply -f https://docs.projectcalico.org/manifests/calico.yaml
