---

- name: Create Kustomize directory
  file:
    path: "{{ kustomize_path }}"
    state: directory

- name: Copy kustomization.yml to Kustomize directory
  copy:
    src: "files/coredns-patch/kustomization.yml"
    dest: "{{ kustomize_path }}/kustomization.yml"

- name: Copy coredns-patch.yml to Kustomize directory
  copy:
    src: "files/coredns-patch/coredns-patch.yml"
    dest: "{{ kustomize_path }}/coredns-patch.yml"

- name: Apply the Kustomize patch for CoreDNS
  command: kubectl apply -k "{{ kustomize_path }}"
  become: yes
  notify: Restart CoreDNS
