---

- name: Creates "/etc/apt/keyrings" directory
  file:
    path: /etc/apt/keyrings
    state: directory

- name: Download Kubernetes signing key for the new repository
  get_url:
    url: https://pkgs.k8s.io/core:/stable:/v1.28/deb/Release.key
    dest: /tmp/kubernetes-release.key

- name: Add Kubernetes signing key
  command: gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg /tmp/kubernetes-release.key
  args:
    creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: Adding new Kubernetes repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.28/deb/ /"
    state: present
    filename: kubernetes.list

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install kubelet, kubeadm, and kubectl
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - kubelet
    - kubeadm
    - kubectl

- name: Configure node ip
  lineinfile:
    path: /etc/default/kubelet
    line: KUBELET_EXTRA_ARGS=--node-ip={{ ansible_default_ipv4.address }}
    create: yes

- name: Restart kubelet
  service:
    name: kubelet
    daemon_reload: yes
    state: restarted

- name: Deploy aliases
  template:
    src: "aliases.j2"
    dest: "/home/{{ ansible_user }}/.bash_aliases"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Ensure .bashrc sources .bash_aliases
  lineinfile:
    path: "/home/{{ ansible_user }}/.bashrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
    line: "source /home/{{ ansible_user }}/.bash_aliases"
    insertafter: "EOF"
    state: present
