---
- name: Check if the Kubernetes cluster is correctly initialized
  command: kubectl cluster-info
  environment:
    KUBECONFIG: "/home/{{ k8s_admin_user }}/.kube/config"
  register: cluster_info
  changed_when: false
  ignore_errors: yes

- name: Display cluster info
  debug:
    msg: "{{ cluster_info.stdout }}"
  when: cluster_info.rc == 0

- name: Fail if cluster is not correctly initialized
  fail:
    msg: "Cluster initialization failed."
  when: cluster_info.rc != 0

- name: List all nodes in the cluster
  command: kubectl get nodes
  environment:
    KUBECONFIG: "/home/{{ k8s_admin_user }}/.kube/config"
  register: nodes_list
  changed_when: false

- name: Display nodes list
  debug:
    msg: "{{ nodes_list.stdout }}"