---

- name: Add the GPG key for Docker
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add the repository to fetch the Docker package
  command: 'echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/debian bullseye stable" | tee /etc/apt/sources.list.d/docker.list'

- name: add apt key for docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    
- name: Install Docker
  apt:
    name:
      - docker
      - docker.io
      - docker-compose
      - docker-registry
    state: latest
    update_cache: true

- name: Create network
  docker_network:
    name: mynetwork

- name: Create Docker group
  group:
    name: docker
    state: present

- name: Add ssh to Docker group
  user:
    name: "{{ ansible_user }}" 
    groups: docker
    append: yes

- name: Restart Docker service
  service:
    name: docker
    state: restarted